language: python
jobs:
  include:
    - name: "python 3.8 on Linux"
      python: "3.8"
    - name: "python 3.9 on Linux"
      python: "3.9"
install:
  - pip3 install -U pip
  - pip3 install -r requirements.txt
script:
  - python3 install.py --travis-ci --gen-script
  - cat run.sh
